name: CI

on:
  pull_request:
    branches: [main]

jobs:
  typos-check:
    name: Typos Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: crate-ci/typos@cfe759ac8dd421e203cc293a373396fbc6fe0d4b # v1.22.7

  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: 'bazel run //tools/format:format.check'

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: 'bazel build //...'

