name: CI

on:
  pull_request:
    branches: [main]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: greut/eclint-action@v0
      with:
        # exclude files handled by prettier
        eclint_args: >-
          -exclude=**/*.ts
          -exclude=**/*.html
          -exclude=**/*.scss
    - run: 'bazel run @pnpm -- --dir $PWD run format:check'

