on: workflow_dispatch

jobs:
  update_ecsact_sdk:
    name: 'Update Ecsact SDK'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazel run //scripts:update_ecsact_sdk
      - run: |
        git add firebase.json &&
        git commit -m "" &&
        git push ||
        echo no updates
